<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido [
    <!ELEMENT pedido (destinatario, articulo, direccion_entrega, fecha_entrega)>
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT articulo (#PCDATA)>
    <!ELEMENT direccion_entrega (#PCDATA)>
    <!ELEMENT fecha_entrega (#PCDATA)>
]>

<pedido>
    <destinatario>Juan Delgado Mart√≠nez</destinatario>
    <articulo>Bicicleta Bianchi Oltre</articulo>
    <direccion_entrega>calle Reforma 423, tercer piso, letra A</direccion_entrega>
    <fecha_entrega>19-09-2021</fecha_entrega>
</pedido>
